In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"..\DATA\HR_Analytics_Cleaned_Master.csv")

In [4]:
df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeID,Gender,JobLevel,...,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating,Education_Label,JobSatisfaction_Label,EnvironmentSatisfaction_Label,WorkLifeBalance_Label,PerformanceRating_Label
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,Female,1,...,3.0,4.0,2.0,3,3,College,Very High,High,Good,Excellent
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,2,Female,1,...,3.0,2.0,4.0,2,4,Below College,Medium,High,Best,Outstanding
2,32,No,Travel_Frequently,Research & Development,17,4,Other,3,Male,4,...,2.0,2.0,1.0,3,3,Master,Medium,Medium,Bad,Excellent
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,4,Male,3,...,4.0,4.0,3.0,2,3,Doctor,Very High,Very High,Better,Excellent
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,5,Male,1,...,4.0,1.0,3.0,3,3,Below College,Low,Very High,Better,Excellent

In [3]:
df.dtypes

Age                                int64
Attrition                         object
BusinessTravel                    object
Department                        object
DistanceFromHome                   int64
Education                          int64
EducationField                    object
EmployeeID                         int64
Gender                            object
JobLevel                           int64
JobRole                           object
MaritalStatus                     object
MonthlyIncome                      int64
NumCompaniesWorked               float64
PercentSalaryHike                  int64
StockOptionLevel                   int64
TotalWorkingYears                float64
TrainingTimesLastYear              int64
YearsAtCompany                     int64
YearsSinceLastPromotion            int64
YearsWithCurrManager               int64
EnvironmentSatisfaction          float64
JobSatisfaction                  float64
WorkLifeBalance                  float64
JobInvolvement                     int64
PerformanceRating                  int64
Education_Label                   object
JobSatisfaction_Label             object
EnvironmentSatisfaction_Label     object
WorkLifeBalance_Label             object
PerformanceRating_Label           object
dtype: object

In [5]:
df.shape

(4327, 31)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4327 entries, 0 to 4326
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            4327 non-null   int64
 1   Attrition                      4327 non-null   object
 2   BusinessTravel                 4327 non-null   object
 3   Department                     4327 non-null   object
 4   DistanceFromHome               4327 non-null   int64
 5   Education                      4327 non-null   int64
 6   EducationField                 4327 non-null   object
 7   EmployeeID                     4327 non-null   int64
 8   Gender                         4327 non-null   object
 9   JobLevel                       4327 non-null   int64
 10  JobRole                        4327 non-null   object
 11  MaritalStatus                  4327 non-null   object
 12  MonthlyIncome                  4327 non-null   int64
 13  NumCompaniesWorked             4327 non-null   float64
 14  PercentSalaryHike              4327 non-null   int64
 15  StockOptionLevel               4327 non-null   int64
 16  TotalWorkingYears              4327 non-null   float64
 17  TrainingTimesLastYear          4327 non-null   int64
 18  YearsAtCompany                 4327 non-null   int64
 19  YearsSinceLastPromotion        4327 non-null   int64
 20  YearsWithCurrManager           4327 non-null   int64
 21  EnvironmentSatisfaction        4327 non-null   float64
 22  JobSatisfaction                4327 non-null   float64
 23  WorkLifeBalance                4327 non-null   float64
 24  JobInvolvement                 4327 non-null   int64
 25  PerformanceRating              4327 non-null   int64
 26  Education_Label                4327 non-null   object
 27  JobSatisfaction_Label          4327 non-null   object
 28  EnvironmentSatisfaction_Label  4327 non-null   object
 29  WorkLifeBalance_Label          4327 non-null   object
 30  PerformanceRating_Label        4327 non-null   object
dtypes: float64(5), int64(14), object(12)
memory usage: 1.0+ MB

In [7]:
df.describe()

,Age,DistanceFromHome,Education,EmployeeID,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating
count,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000
mean,36.916570,9.186966,2.913797,2208.812803,2.067021,65029.244280,2.689161,15.210307,0.794777,11.272244,2.796626,7.020337,2.185810,4.128264,2.724520,2.724983,2.761498,2.727987,3.153686
std,9.143345,8.092618,1.024080,1273.370663,1.107342,46976.222828,2.491730,3.658903,0.853017,7.779457,1.288936,6.140673,3.227776,3.563110,1.092955,1.101498,0.706921,0.711318,0.360689
min,18.000000,1.000000,1.000000,1.000000,1.000000,10090.000000,0.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,3.000000
25%,30.000000,2.000000,2.000000,1105.500000,1.000000,29260.000000,1.000000,12.000000,0.000000,6.000000,2.000000,3.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000
50%,36.000000,7.000000,3.000000,2212.000000,2.000000,49360.000000,2.000000,14.000000,1.000000,10.000000,3.000000,5.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
75%,43.000000,14.000000,4.000000,3312.500000,3.000000,83805.000000,4.000000,18.000000,1.000000,15.000000,3.000000,9.000000,3.000000,7.000000,4.000000,4.000000,3.000000,3.000000,3.000000
max,60.000000,29.000000,5.000000,4409.000000,5.000000,199990.000000,9.000000,25.000000,3.000000,40.000000,6.000000,40.000000,15.000000,17.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [8]:
df["EmployeeID"].duplicated().sum()

0

In [9]:
df.isna().sum()

Age                              0
Attrition                        0
BusinessTravel                   0
Department                       0
DistanceFromHome                 0
Education                        0
EducationField                   0
EmployeeID                       0
Gender                           0
JobLevel                         0
JobRole                          0
MaritalStatus                    0
MonthlyIncome                    0
NumCompaniesWorked               0
PercentSalaryHike                0
StockOptionLevel                 0
TotalWorkingYears                0
TrainingTimesLastYear            0
YearsAtCompany                   0
YearsSinceLastPromotion          0
YearsWithCurrManager             0
EnvironmentSatisfaction          0
JobSatisfaction                  0
WorkLifeBalance                  0
JobInvolvement                   0
PerformanceRating                0
Education_Label                  0
JobSatisfaction_Label            0
EnvironmentSatisfaction_Label    0
WorkLifeBalance_Label            0
PerformanceRating_Label          0
dtype: int64